### ISSUE TITLE
Static library only works for i86 archs

### ISSUE THREAD

**Issue by ospfranco** [jerson/react-native-fast-openpgp#100]
I noticed once the library is added one can only run the app when running it with rosetta (on apple silicon machines). While this might work, it's dirty. You should compile the library (or download per target .a files). You can then package all of them in an xcframework (because x86 and x86_64 clash and you cannot directly include them) and use the `vendored_frameworks` capability of cocoapods to require this framework and xcode will compile per architecture.

You can see an example of how to do this (in Rust, but the concept is the same) [in this post](https://ospfranco.com/post/2023/08/11/react-native,-rust-step-by-step-integration-guide/)

**Comment by jerson** [comment]
Hi @ospfranco yeah xcframework is something I'm gonna need to implement, going to check the docs to see how I can update the native code builder https://github.com/jerson/openpgp-mobile

**Comment by gituser8796** [comment]
Hi @jerson , is it something you'll be able to do in the near future?

**Comment by jerson** [comment]
hey @gituser8796   @ospfranco   could you try the newest version, I migrated to xcframework to support iphonesimulator
https://www.npmjs.com/package/react-native-fast-openpgp/v/2.7.3

**Comment by ospfranco** [comment]
Sorry, I don't have access to the project anymore. But if you followed the instructions it should be fine. Thanks!
