### ISSUE TITLE
The iOS build fails after installing react-native-fast-openpgp.

### ISSUE THREAD

**Issue by harshad-wedo** [jerson/react-native-fast-openpgp#106]
Hi @jerson
When attempting to build app for iOS, I'm encountering the following error:

fastOpenPGP::install(facebook::jsi::Runtime&)::$_1::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda'(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in react_native_fast_openpgp[4](https://github.com/jerson/react-native-fast-openpgp/issues/react-native-fast-openpgp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Kyle772** [comment]
+1 I was able to get it to work on a physical iOS device in the meantime but there is something wrong here.

For context I'm on M1

**Comment by jerson** [comment]
hey @Kyle772  @harshad-wedo  could you try the newest version, I migrated to xcframework to support iphonesimulator
https://www.npmjs.com/package/react-native-fast-openpgp/v/2.7.3
