### ISSUE TITLE
problems with creating Android Release

### ISSUE THREAD

**Issue by haralddoderer** [jerson/react-native-fast-openpgp#19]
Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting A
AR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-fast-openpgp project caused this error

buildscript {
    ext {
        buildToolsVersion = "30.0.0"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 29
        supportLibVersion = "28.0.0"
        ndkVersion = "20.1.5948944"
        googlePlayServicesVersion = "11+"
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.1.0")
        classpath 'com.google.gms:google-services:4.3.5'
    }
}

"react": "17.0.1",
"react-native": "0.63.4",

**Comment by jerson** [comment]
hi @haralddoderer thanks for report this issue, recently im working on a branch without .aar (using flatbuffers  .so) so probably after this we can solve this issue

**Comment by jerson** [comment]
maybe is too late but i released a new rc version using shared libraries to solve this issue

https://www.npmjs.com/package/react-native-fast-openpgp/v/2.0.0-rc1

if you could test would be great. :D

**Comment by se1exin** [comment]
@jerson I've just tested `2.0.0-rc1` out on both Android and iOS, debug and release, and it's building and working for me (RN 64).

I tested both as fresh installs, and upgrading existing installs that were previously using `1.6.3` and had keys from that version in-use - both use cases work without error on both Android and iOS 🥳.

Please ping me when you release `2.0.0` so I can update my deps to point to the new version 😄
