### ISSUE TITLE
Can't install library

### ISSUE THREAD

**Issue by Alex-queval** [jerson/react-native-fast-openpgp#2]
Hello,

I have a problem, install the library with **Node** or **Yarn**.

With node i am getting this error :

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-fast-openpgp@0.4.4 postinstall: `cd ios/native && unzip -o Openpgp.framework.zip`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-fast-openpgp@0.4.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

With yarn:

'unzip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jerson** [comment]
Hi, @Alex-queval  it seems you need to install `unzip` on your operating system:

ubuntu, debian or the like:
```bash
apt install unzip
```
centos, redhat:
```bash
yum install unzip
```

note: unzip is required to be able to decompress the framework used for ios compilation

**Comment by Alex-queval** [comment]
Thank you so much @jerson for your response.

Unfortunately i am working on windows not on a Linux distribution.

**Comment by jerson** [comment]
@Alex-queval you can also install on windows with 

```bash
scoop install unzip
``` 
don't forget add scoop bin dir to env path

**Comment by poltak** [comment]
This is happening to me as well on v0.5.0 with both yarn and npm. I do not get the `'unzip' is not recognized as an internal or external command,
operable program or batch file.` message. `unzip` is available in my `PATH`

**Comment by jerson** [comment]
Hi @poltak, please can you run this command and show the output here 
```
which unzip
```

**Comment by jerson** [comment]
Hi @Alex-queval and @poltak  i just upload a new version v0.6.0 with library for unzip without native binaries

https://www.npmjs.com/package/react-native-fast-openpgp/v/0.6.0
