### ISSUE TITLE
Bitcode support

### ISSUE THREAD

**Issue by jdmunro** [jerson/react-native-fast-openpgp#3]
Is there a reason to disable bitcode support on iOS?

https://github.com/jerson/react-native-fast-openpgp/blob/master/react-native-fast-openpgp.podspec#L21

**Comment by jerson** [comment]
Hi @jdmunro, this openpgp library was made with golang and gomobile, gomobile allow compile a framework for ios but unfortunately it don't support bitcode

**Comment by jdmunro** [comment]
@jerson Makes sense, thanks! As I understand it, they now have support for bitcode: https://github.com/golang/mobile/commit/9487ef54b94ae47ddae17f17624fe8ad8aaba55f

Some other libraries are now supporting it, e.g: https://github.com/DimensionDev/Tessercube-iOS/issues/48 (So it might be possible to support it now)

Bitcode will eventually become mandatory to submit iOS apps to the store.

**Comment by jerson** [comment]
@jdmunro thank you, I did not know, these days I will update the library to support bitcode :D

**Comment by jerson** [comment]
hi @jdmunro  i just release v0.5.0 with new binaries with bitcode support, i just tested using this command
```bash
otool -arch arm64 -l MyFramework.framework/MyFramework | grep -a4 __LLVM

```

just update you package.json

npm link: https://www.npmjs.com/package/react-native-fast-openpgp/v/0.5.0

**Comment by jdmunro** [comment]
Thanks @jerson I can confirm that works 🎉
