### ISSUE TITLE
How can I upgrade openpgp-mobile version?

### ISSUE THREAD

**Issue by Chi-AnTai** [jerson/react-native-fast-openpgp#33]
Hi, 
I have problem using encrypt and get `openpgp: invalid argument: cannot encrypt because no candidate hash functions are compiled in. (Wanted RIPEMD160 in this case.)`, which is similar to [this issue](https://github.com/jerson/openpgp-mobile/issues/12)

I think upgrade openpgp-mobile to latest version may solve this issue but the upgrade script is not working for me, is there some other way to upgrade it?

Thank!

**Comment by jerson** [comment]
hi @Chi-AnTai  thanks for the question, in order to update libs, you need to run

`make upgrade-libs`
 btw im updating right now, and i will release a new version soon

**Comment by JungHsuan** [comment]
> hi @Chi-AnTai thanks for the question, in order to update libs, you need to run
> 
> `make upgrade-libs` btw im updating right now, and i will release a new version soon

Hi @jerson, thanks for this great work.
I am also facing this problem. 
I would like to know if version 2.0.1 solves this problem?
Thank you!
