### ISSUE TITLE
Doesn't work with Xcode 13

### ISSUE THREAD

**Issue by IlyaDylko** [jerson/react-native-fast-openpgp#34]
When I'm trying to build the app I get this error.
Undefined symbols for architecture x86_64:
  "facebook::jsi::Value::Value(facebook::jsi::Runtime&, facebook::jsi::Value const&)", referenced from:
      facebook::jsi::detail::toValue(facebook::jsi::Runtime&, facebook::jsi::Value const&) in react-native-fast-openpgp.o

**Comment by jerson** [comment]
Hi @IlyaDylko thanks for report the issue, I will check that next week, bc this week im on vacation

**Comment by jerson** [comment]
hi @IlyaDylko please can you run `react-native info`, i just tested localy with 2.0.0 and is working for me
```shell
➜  example git:(master) ✗ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 12.0.1
    CPU: (4) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 207.83 MB / 10.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.3/bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 30
      Build Tools: 30.0.2
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Arctic Fox 2020.3.1 Patch 3 Arctic Fox 2020.3.1 Patch 3
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

**Comment by IlyaDylko** [comment]
Hi @jerson ! It seems the problem occurred only on one specific project and it was related to some custom settings. Sorry, I had to check that before posting. Everything works fine :)

**Comment by harshad-wedo** [comment]
Hi @jerson 
When attempting to build app for iOS, I'm encountering the following error:

 fastOpenPGP::install(facebook::jsi::Runtime&)::$_1::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda'(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in react_native_fast_openpgp[4](react-native-fast-openpgp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
