### ISSUE TITLE
TypeError: null is not an object (evaluating 'FastOpenPGPNativeModules.call')

### ISSUE THREAD

**Issue by mcf7** [jerson/react-native-fast-openpgp#36]
I am calling OpenPGP.verify in an android app and getting an error
TypeError: null is not an object (evaluating 'FastOpenPGPNativeModules.call')
What is going on here? I have imported the module:
import OpenPGP from 'react-native-fast-openpgp';
and am doing
OpenPGP.verify(s, d, k).then((value) => { console.log("OK: "); }, (reason) => { console.log("Failed: " + reason.toString())}).catch(()=> { console.log("EXCEPTION")});
}) (data);

**Comment by jerson** [comment]
Hi @mcf7 thanks for report the issue, I will check that next week, bc this week im on vacation

**Comment by jerson** [comment]
Hi, have you tried using 

```ts
import OpenPGP from "react-native-fast-openpgp";

OpenPGP.useJSI = true;
```

also could you run `react-native info`

**Comment by jerson** [comment]
seems like is an autolinking issue, for now the fix is

```
npx react-native link react-native-fast-openpgp
cd ios && pod install
```

im gonna check docs about linking probably something has changed

**Comment by jerson** [comment]
im closing this for now but feel free to reopen if you have more questions

**Comment by mcf7** [comment]
I still can't get this to work.
In the App attached below (simple test app, should run in a web browser)

With the OpenPGP.useJSI = true; line I get the error
Failed: TypeError: global.FastOpenPGPCallPromise is not a function 

Without the OpenPGP.useJSI commented out I get the error
Failed: TypeError: Cannot read properties of undefined (reading 'call')

[App.js.txt](https://github.com/jerson/react-native-fast-openpgp/files/7664745/App.js.txt)

**Comment by jerson** [comment]
Hi @mcf7 seems like you are using expo, we currenty dont support expo, thats the reason why is not working for you.

**Comment by happyjosh** [comment]
Hi，Have you been resolved this problem? I ran into the same problem.

**Comment by ChauVV** [comment]
how can i run on expo?

**Comment by rares-lupascu** [comment]
same here ... react-native not expo

**Comment by nguyenvanphuc2203** [comment]
same here, react native cli 0.72.1, please help @jerson 

![image_2024-02-25_11-57-28](https://github.com/jerson/react-native-fast-openpgp/assets/33291479/f02129cf-90e6-4ed8-9dcb-55e87e083594)

**Comment by jerson** [comment]
Hi @nguyenvanphuc2203 which library version are you using? We recently released a new version a month ago, if you are using latest, could you try the one before

**Comment by nguyenvanphuc2203** [comment]
> Hi @nguyenvanphuc2203 which library version are you using? We recently released a new version a month ago, if you are using latest, could you try the one before

hi, thank you for reply,
im using lastest version 2.7.2 with react-native cli 0.72
so i dont know how to resolve this problem
And i tried to used 2.7.1 and 2.7.0 but still got this issue

**Comment by Matthew-Oluwajuwon** [comment]
Getting the issue too

 ERROR  Test failed: [TypeError: Cannot read property 'install' of null]
 
 using version 2.7.3
 
  const testOpenPGP = async () => {
    try {
      if (OpenPGP.encrypt) {
        console.log("Encrypt method is available.");
        const result = await OpenPGP.encrypt('Test message', '-----BEGIN PGP PUBLIC KEY BLOCK-----...');
        console.log('Encryption result:', result);
      } else {
        console.error('Encrypt method is not available.');
      }
    } catch (error) {
      console.error('Test failed:', error);
    }
  };
  
  testOpenPGP();
