### ISSUE TITLE
Default key options

### ISSUE THREAD

**Issue by jdmunro** [jerson/react-native-fast-openpgp#4]
Would you mind clarifying the default key options? It wasn't clear from the docs or from reading the code about what would be used if you don't specify the options manually.

**Comment by jerson** [comment]
hi @jdmunro, i just updated docs:

```typescript
export interface KeyOptions {
  /**
   * required
   */
  RSABits: 2048 | 4096 | 1024;

  /**
   * default: aes128
   */
  cipher?: "aes128" | "aes192" | "aes256";

  /**
   * default: none
   */
  compression?: "none" | "zlib" | "zip";

  /**
   * default: sha256
   */
  hash?: "sha256" | "sha224" | "sha384" | "sha512";

  /**
   * default: 0
   */
  compressionLevel?: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
}
```

source file: 

https://github.com/jerson/react-native-fast-openpgp/blob/master/src/index.tsx#L5-L30

**Comment by jdmunro** [comment]
@jerson Is there no default for the `RSABits` too? I have a project where I'm not passing a key options currently, so I wondered what the value is. Thanks for updating!

**Comment by jerson** [comment]
@jdmunro when you dont passing RSABits by default is 2048: 

``` go
	// RSABits is the number of bits in new RSA keys made with NewEntity.
	// If zero, then 2048 bit keys are created.
	RSABits int
```
