### ISSUE TITLE
Unable to encrypt with certain public keys

### ISSUE THREAD

**Issue by GarethABerry** [jerson/react-native-fast-openpgp#42]
When I use the private key from the example in the source code the encryption works. I am calling 
`OpenPGP.encrypt(message, publicKey) `
and the aforementioned public key is 

`-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBF0Tpe0BCADm+ja4vMKuodkQEhLm/092M/6gt4TaKwzv8QcA53/FrM3g8wab
oksgIN1T+CscKXOY9GeJ530sBZgu9kTsMeQW3Uf76smo2CV1W7kSTMU+XE5ExGET
+LhkKeHpXoLfZNegKuzH1Qo7DGDOByVrnijbZIukonGwvC/MTduxb69ub+YRhWJc
fCjpMhm4WsC4h0Oz3ir5kx6NsN7XGVT5ghR9OEV6jlFmJ1nYYQxMlBGiATN5f2VR
Y/T9QBLOEsLNvK4OqviLVvgPTQZBePoCeL73CxTbqVhcamvFRVicivl8AphDLATn
1HlIjsTtbH5I/STb8UUdL+4ziRzsQukEw++xABEBAAG0WFRlc3QgQ2xpZW50IFBy
ZXBhZ28gKExsYXZlIGRlIGNsaWVudGUgdXRpbGl6YWRhIGVuIHRlc3QgYXV0b21h
dGl6YWRvcykgPGNsaWVudEB0ZXN0LmNvbT6JAU4EEwEIADgWIQSM7S4gtzn4Xwz9
EH+B0DnjYl2BcAUCXROl7QIbAwULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAKCRCB
0DnjYl2BcI1HB/94YttYwwEDYeaD51gX9QamH2DsayAqPsKyEHmgsJdJcCK27sPb
EjrI3g8sKze2aG6hPgY+FjLp/sCXWayt8N1wN7U7gnFCu2cszykyTKMwTuZs06w5
LEWWWZG3WcbVU4EdNVN0sCYr1OfgQiI9CT7/H5HZM12m5u4Qgw+9CFyMBb9sPjMw
KBMHnQLkp/J0Fmiy5KTdZL+o28lfttAOJDg+ZTChs0LWnvZCrLKquIkX7ugI85iZ
leehaFWX5Bx9w9D06uERbFlWxlonR94aA9oX9rjXcaNZeDRSpHqh5JlTMSrXXT1k
LVNLZieBhA033eNaPwMFuKyAlnVBV9d/Qz7guQENBF0Tpe0BCAD3L3Wizb8XHQAb
UXPqUe4Uc3YpRCXr/1wkIe7atDIP0Y74uxeklHMPFhxO+8pBL/bDrh+4ojdjDW8R
uE3tgSTDp5Jx4YG32dHwpoTZ1n9N8Fc58MY3zju3n2J3N86vNkST/qDzKEf7SUfi
u+KE0x3+U0QUostL9iVJXa4zg+te0yTqCt8IzGbQ6g6qCNxbbb9bZi+xDdl8z3f+
+oYIMhakixuwgDsWMblbLH7yE0gkMzEP5P5C1MsR7Ty1rtKL6RPsPvqbCXjiqI2y
iRrwAFEX1zQhqZrFRyVkzM1uQRGqFV9IDDowK44kxezumS7JLFgrZzrQFY0oOhpz
oNrWxkalABEBAAGJATYEGAEIACAWIQSM7S4gtzn4Xwz9EH+B0DnjYl2BcAUCXROl
7QIbDAAKCRCB0DnjYl2BcHlcB/45ISlU8Fjp0JewpZV5gLj2aExDwzJHhjZioay0
S+FS7jSu3Q7fmh1IDQdk6k0++v31YhMJt/96W4coH3hBBMuU+nCM4Ed6g9TAlhSQ
RQdxDY2bYSHnYP4wLZ1JMB3SL9vEsfUS+M+NYS6VxkaVo4opwM6AMBxoFfQj+41F
s5OVkk68O6f4Rd2HInd0DnGQJvTFF1iDTRvPbtmU7hE088yxpGkHudeLtnasqXSZ
jPnzaV0g4yjKXlsZYDS8PcyFSfho1FX7IHsPwCxPZcEqcRUa6qQ6J5X9B/N09N0i
D4m65Neoc7DBEdvzgK9IUMpwG5N0t+0pfWLhs8AZdMxE7RbP
=kbtq
-----END PGP PUBLIC KEY BLOCK-----`

Though when I use another public key 
`-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEXqGR6RYJKwYBBAHaRw8BAQdAyvNkBTmHtu6Gd7FeQUQbTtC/kF4V2TQnA6C8
qAm4/Gu0MkludmljdHVzIENhcGl0YWwgU2VjcmV0cyA8cmF5QGludmljdHVzY2Fw
aXRhbC5jb20+iJAEExYIADgWIQSBLGtZpyp0O5xzwbRy7t7peZ4rYQUCXqGR6QIb
IwULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAKCRBy7t7peZ4rYYmHAP0QfyLeLa1Q
gL+kxbly2WbIs7qNidI/pp0Gh4qnc6dWXgD9Ed7TAqIQz2cFT66kYg0JkAGnXxyS
GjwqGxzty0ayHg+4OAReowh3EgorBgEEAZdVAQUBAQdAJvHX60UM7gLnIXIbPb1s
HL8ZArhCudR93llcbXZ43AQDAQgHiHgEGBYIACAWIQSBLGtZpyp0O5xzwbRy7t7p
eZ4rYQUCXqMIdwIbDAAKCRBy7t7peZ4rYcwkAQDgn+3gZu3PhifiFyTuDj7mlxlH
5+lJO/cpura0wDB0CgEA1CuBq7H3MVI+BuQ+akQebVeosTjJgC7VDFFlVxsaGQY=
=3hhY
-----END PGP PUBLIC KEY BLOCK-----`

I received this error from 
`StringResponse.getRootAsStringResponse(result);`
`[Error: Error: stringResponse: publicKey error: openpgp: unsupported feature: public key type: 22]`

Any assistance with this would be greatly appreciated.
Thanks in advanced

**Comment by jerson** [comment]
Hi @GarethABerry thanks for report this, I just updated internal library and seems works could you try using
v2.2.0 version
https://www.npmjs.com/package/react-native-fast-openpgp/v/2.2.0

**Comment by GarethABerry** [comment]
I can confirm my ECDH public key and message was successfully encrypted. Thank you so much!
