### ISSUE TITLE
ReferenceError: Can't find variable: BigInt

### ISSUE THREAD

**Issue by se1exin** [jerson/react-native-fast-openpgp#59]
Hi there, when attempting to use either ` OpenPGP.encryptFile` or `OpenPGP.decryptFile` the error `ReferenceError: Can't find variable: BigInt` is thrown.

Versions: 
```
"react-native": "0.68.0",
"react-native-fast-openpgp": "2.2.3"
```

Hermes is not enabled.

This is happening on Android, I haven't tested iOS yet.

**Comment by se1exin** [comment]
After further debugging I have found that the JSC used by React Native doesn't actually support `BigInt` (see https://github.com/facebook/react-native/issues/28492).

I have fixed this by shimming BigInt using the `big-integer` package, in a similar way to this comment: https://github.com/facebook/react-native/issues/28492#issuecomment-824698934

Here's what I did:

`yarn add big-integer`

Create a file `shim.js` in the root of my React Native project, with the contents:

```
if (typeof BigInt === 'undefined') {
  const bigInt = require('big-integer');
  bigInt.asUintN = function (bits, bigint) {
    bigint = bigInt(bigint);
    if (typeof bigint.value === 'bigint') {
      return bigInt(BigInt.asUintN(bits, bigint.value));
    }
    const p2bits = bigInt(1).shiftLeft(bits);
    const mod = bigint.and(p2bits.subtract(1));
    return mod;
  };
  bigInt.asIntN = function (bits, bigint) {
    bigint = bigInt(bigint);
    if (typeof bigint.value === 'bigint') {
      return bigInt(BigInt.asIntN(bits, bigint.value));
    }
    const p2bits = bigInt(1).shiftLeft(bits);
    const mod = bigint.and(p2bits.subtract(1));
    return mod.greaterOrEquals(p2bits.subtract(mod))
      ? mod.subtract(p2bits)
      : mod;
  };
  global.BigInt = bigInt;
}
```

Then import the shim in my `index.js` file:

```
import './shim';

... rest of app init code
```

**Comment by jerson** [comment]
btw, finally those changes are included in https://www.npmjs.com/package/react-native-fast-openpgp/v/2.3.0
