### ISSUE TITLE
Error calling functions on expo

### ISSUE THREAD

**Issue by jrocca82** [jerson/react-native-fast-openpgp#60]
When running the "generate" function on expo, creates the error "null is not an object (evaluating 'FastOpenPGPNativeModules.call')".

Adding 
`OpenPGP.useJSI = true;`
creates the error "global.FastOpenPGPCallPromise is not a function. (In 'global.FastOpenPGPCallPromise(name, buff)', 'global.FastOpenPGPCallPromise' is undefined)"

**Comment by jerson** [comment]
Hi @jrocca82 thanks for report the issue, this library doesn´t support expo so far, so thats why is failing
