### ISSUE TITLE
Generate a public key from a private key?

### ISSUE THREAD

**Issue by bitcoinbrisbane** [jerson/react-native-fast-openpgp#65]
Some users already have a private key.  Would be great to be able to generate a public key from a private key, such as "readKey" and then `.toPublicKey()` in this JS implementation?

https://github.com/openpgpjs/openpgpjs/blob/6c32b62ef3b36527086a2551f4bfa8437c8175e4/test/general/openpgp.js#L902

```javascript
  const result: openpgp.Key = await openpgp.readKey({ armoredKey: privateKey });
  const publicKey = result.toPublic();
```

Could we extend the interface to be something like this?

```javascript
    static async import(inputFile: string): Promise<KeyPair> {
        const builder = new flatbuffers.Builder(0);
        KeyPair.createKeyPair(builder, 0, 0);
        const result = await this.call('createKeyPair', builder.asUint8Array());
        return this._keyPairResponse(result);
    }
```

**Comment by jerson** [comment]
Hi @bitcoinbrisbane I just release a new version with some new functions, you can use this new one

```ts
const publicKey = await OpenPGP.convertPrivateKeyToPublicKey(privateKey: string): Promise<string>;
```

see: https://www.npmjs.com/package/react-native-fast-openpgp/v/2.4.0

**Comment by bitcoinbrisbane** [comment]
Amazing!  Ill check out the latest commit and happy to make PRs if i can work it out.

**Comment by xiangzhe0812** [comment]
![Screen Shot 2022-07-06 at 11 45 38 am](https://user-images.githubusercontent.com/1115763/177449522-27650f91-5b53-4662-b62a-2b2d494fb4f2.png)
@jerson  only got half of the public key.

**Comment by jerson** [comment]
@xiangzhe0812 yeah my bad, gonna fix in some mins :D

**Comment by jerson** [comment]
Hi @xiangzhe0812 please try with v2.4.1 I just released to npm

just for the record, this was the change https://github.com/jerson/openpgp-mobile/commit/f34094d078aa93544383404461adc584243f9dc0

**Comment by bitcoinbrisbane** [comment]
> Hi @xiangzhe0812 please try with v2.4.1 I just released to npm
> 
> just for the record, this was the change [jerson/openpgp-mobile@f34094d](https://github.com/jerson/openpgp-mobile/commit/f34094d078aa93544383404461adc584243f9dc0)

Thanks @jerson!  Ill have a look at the delta on the commit so I can make PRs in the future.  It'll be good to do some Go again! Ill try add some unit tests too.

**Comment by xiangzhe0812** [comment]
@jerson Thanks. it works really good.
