### ISSUE TITLE
Got error when convertPrivateKeyToPublicKey

### ISSUE THREAD

**Issue by xiangzhe0812** [jerson/react-native-fast-openpgp#69]
Got error when convertPrivateKeyToPublicKey, it worked month ago, not sure why its not working.
@jerson any Idea?

![Screenshot_20220808-112532](https://user-images.githubusercontent.com/1115763/183321211-0db36337-5b68-454b-936d-845e4142a2c6.jpg)

**Comment by jerson** [comment]
hi @xiangzhe0812 which version are you using ?

**Comment by xiangzhe0812** [comment]
> hi @xiangzhe0812 which version are you using ? 

Hey @jerson  im using the lasted version 2.4.1

**Comment by jerson** [comment]
Hi, please try using latest or share an sample key here please

**Comment by xiangzhe0812** [comment]
Thanks @jerson
