### ISSUE TITLE
Remove jcenter() from ./android/build.gradle

### ISSUE THREAD

**Issue by penghuili** [jerson/react-native-fast-openpgp#75]
Thanks for this great library!

One problem I noticed this morning is, I can't run / build the android version, because jcenter is down, I get this error message:
![Screenshot 2022-10-30 at 13 13 29](https://user-images.githubusercontent.com/5326739/198878109-7e35816d-e6a6-4ea9-94db-dabc3051ae8e.png)

But after I remove `jcenter()` from `./android/build.gradle`, things start working again:
https://github.com/jerson/react-native-fast-openpgp/blob/v2.5.0/android/build.gradle#L8
https://github.com/jerson/react-native-fast-openpgp/blob/v2.5.0/android/build.gradle#L75

Since jcenter is deprecated, i guess it's better not using it in this lib.
What do you think?

(btw, I was using [nodejs-mobile-react-native](https://github.com/nodejs-mobile/nodejs-mobile-react-native) and ran pure [openpgpjs](https://github.com/openpgpjs/openpgpjs) in my app. But this solution made my app's bundle very big, 80+MB. With your lib, my app's size decreases to 20+MB. And it's easier to use and faster. So thanks again!)

**Comment by jerson** [comment]
Hi @penghuili thanks for report this, yes this is something I definetly gonna do

**Comment by jerson** [comment]
Hi, I just released a new version removing jcenter references 
https://www.npmjs.com/package/react-native-fast-openpgp/v/2.5.1

**Comment by penghuili** [comment]
Thanks @jerson !
