### ISSUE TITLE
multi-key encryption

### ISSUE THREAD

**Issue by IanPhilips** [jerson/react-native-fast-openpgp#8]
Hi, thanks for the library. 

Is it possible to encrypt a message with multiple public keys so that any of the private keys can decrypt it?

thanks!

**Comment by jerson** [comment]
Hi @IanPhilips, yes, I think it is possible to implement, this weekend I will investigate how to implement it

**Comment by IanPhilips** [comment]
Nice! From looking at [hybrid-crypto](https://github.com/juhoen/hybrid-crypto-js) it seems like they're encrypting an AES key for each rsa public key and packaging them in a json-like object so that each receiving public key can find a cipher text to decrypt with their private key, returning an AES key that they can use to decrypt the real cipher text that they want to read.

    {
    "v": "hybrid-crypto-js_0.1.2",        // Current package version
    "iv": "CmtyaZTyzoAp1mTNUTztic0v1...", // Initialization vector
    "keys": {                             // Encrypted AES keys by RSA fingerprints
        "85:3d:10:e1:56...": "bHaTF9...",
        "d3:48:6a:e9:13...": "t9eds3..."
    },
    "cipher": "+iwVFsC2dECBQvwcm9DND..."  // Actual encrypted message
    "signature": "sdL93kfdm12feds3C2..."  // Signature (optional)
    }

**Comment by jerson** [comment]
hi @IanPhilips you can encrypt with multiple publicKeys by this way

```javascript
const publicKeys = `
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBF0Tpe0BCADm+ja4vMKuodkQEhLm/092M/6gt4TaKwzv8QcA53/FrM3g8wab
D4m65Neoc7DBEdvzgK9IUMpwG5N0t+0pfWLhs8AZdMxE7RbP
=kbtq
-----END PGP PUBLIC KEY BLOCK-----
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBF0Tpe0BCADm+ja4vMKuodkQEhLm/092M/6gt4TaKwzv8QcA53/FrM3g8wab
D4m65Neoc7DBEdvzgK9IUMpwG5N0t+0pfWLhs8AZdMxE7RbP
=kbtq
-----END PGP PUBLIC KEY BLOCK-----
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBF0Tpe0BCADm+ja4vMKuodkQEhLm/092M/6gt4TaKwzv8QcA53/FrM3g8wab
D4m65Neoc7DBEdvzgK9IUMpwG5N0t+0pfWLhs8AZdMxE7RbP
=kbtq
-----END PGP PUBLIC KEY BLOCK-----
`;
const encrypted = await OpenPGP.encrypt("heyy multiple key" publicKeys);


```

**Comment by IanPhilips** [comment]
@jerson your comment disappeared but is in my email, does that method work or did you purposely delete the comment?

**Comment by IanPhilips** [comment]
btw, this library is indeed MUCH faster than other react-native pgp libaries. I waited 2 minutes for a 2048-bit RSA key from hybrid-crypto whereas yours took a couple seconds!

**Comment by jerson** [comment]
im just updating library for support multiple keys support maybe this weekend should be ready

**Comment by jerson** [comment]
i removed this comment because dont work right now

**Comment by jerson** [comment]
Hi @IanPhilips could you try with latest version please

https://www.npmjs.com/package/react-native-fast-openpgp/v/1.4.1

### Encrypt with multiple keys

```javascript
const publicKeys = `-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBF0Tpe0BCADm+ja4vMKuodkQEhLm/092M/6gt4TaKwzv8QcA53/FrM3g8wab
D4m65Neoc7DBEdvzgK9IUMpwG5N0t+0pfWLhs8AZdMxE7RbP
=kbtq
-----END PGP PUBLIC KEY BLOCK-----
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBF0Tpe0BCADm+ja4vMKuodkQEhLm/092M/6gt4TaKwzv8QcA53/FrM3g8wab
D4m65Neoc7DBEdvzgK9IUMpwG5N0t+0pfWLhs8AZdMxE7RbP
=kbtq
-----END PGP PUBLIC KEY BLOCK-----
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBF0Tpe0BCADm+ja4vMKuodkQEhLm/092M/6gt4TaKwzv8QcA53/FrM3g8wab
D4m65Neoc7DBEdvzgK9IUMpwG5N0t+0pfWLhs8AZdMxE7RbP
=kbtq
-----END PGP PUBLIC KEY BLOCK-----`;
const encrypted = await OpenPGP.encrypt("sample text" publicKeys);
```
