### ISSUE TITLE
Enhance getPublicKeyMetadata to get information about subkeys

### ISSUE THREAD

**Issue by commi** [jerson/react-native-fast-openpgp#80]
Hi, long time happy user here:)

i'm working on a feature where the app exchanges encrypted documents with other apps. Those apps don't always know the user identities. To identity which documents are requested, the key-id is used. but for this to work the app has to know the encryption subkey id (or id's) for a user. (subkeys are optional but often used)

until now i used _openpgp.js_ to inspect keys, but i want of get rid of the dependency because it's a headache:)

would it be possible to enhance `getPublicKeyMetadata` to also return a list of subkeys and theirs id's with the metadata?

**Comment by jerson** [comment]
Hi @commi thanks for suggest this, these weeks I'm quite busy, but I'm going to be implementing in the following weeks, thanks for the patience

**Comment by jerson** [comment]
ref: https://github.com/jerson/openpgp-mobile/pull/30

**Comment by jerson** [comment]
Hi @commi  please take a look to https://github.com/jerson/react-native-fast-openpgp/pull/81 I added identities and subkeys but I want to make sure is what you are looking for

btw this is the version including those changes: https://www.npmjs.com/package/react-native-fast-openpgp/v/2.6.0
