### ISSUE TITLE
openpgp: invalid data: tag byte does not have MSB set

### ISSUE THREAD

**Issue by adigeo** [jerson/react-native-fast-openpgp#89]
Hello,

I am using the latest version of the project.

Using the following code to decrypt a file locally stored:

```
await OpenPGP.decryptFile(file_path, file_path_decrypted, this.state.keys.private).then((content) => {
                    console.log('Decrypted file saved', file_path_decrypted);
                }).catch((error) => {
                    console.log('Decrypting file ', file_transfer.filename, ' error:', error);
                });
```
I get:

```
Decrypting file  FvH1wsSWIAYEwz1.jpeg.asc  error: Error: intResponse: openpgp: invalid data: tag byte does not have MSB set
    at Function._intResponse (index.tsx:713:13)
    at Function.decryptFile$ (index.tsx:265:17)
    at tryCatch (runtime.js:45:40)
    at Generator.invoke [as _invoke] (runtime.js:271:22)
    at prototype.<computed> [as next] (runtime.js:97:21)
    at tryCatch (runtime.js:45:40)
    at invoke (runtime.js:135:20)
    at runtime.js:145:13
    at tryCallOne (core.js:37:12)
    at core.js:123:15
```

**Comment by adigeo** [comment]
Self-solving the problem, the encryptFile and decryptFile functions do not output or read input from PGP-armored text files, calls to the armor/dearmor functions are missing in the underlying go library.

**Comment by nguyenvanphuc2203** [comment]
hello @adigeo how to resolved this issue, a have same issue

**Comment by adigeo** [comment]
See https://github.com/AGProjects/sylk-mobile/blob/master/app/app.js

**Comment by nguyenvanphuc2203** [comment]
> See https://github.com/AGProjects/sylk-mobile/blob/master/app/app.js

hello please tell me your solution, my code same your file

**Comment by nguyenvanphuc2203** [comment]
hi @adigeo i tried your solution format base_64 message work well with text file.json
but i try with .zip file not work, any solution for zip file?
