### ISSUE TITLE
JSI functions cannot be initialized in a threaded manner (race condition)

### ISSUE THREAD

**Issue by ospfranco** [jerson/react-native-fast-openpgp#99]
Hi there. I client is having an issue with this module. When he turned on the JSI flag, he started experiencing a crash on the install method. I took a look and found out the initialization of JSI functions is happening in an async method, but this is basically a race condition, so it will always have a possibility of a thread error.

![sure](https://github.com/jerson/react-native-fast-openpgp/assets/1634213/5c6e99cb-3dd5-4bb7-97da-9ac7e507a29a)

The only way to guarantee the will be no race conditions is to make the `install` function [synchronous and blocking](https://github.com/OP-Engineering/op-sqlite/blob/main/ios/OPSQLite.mm#L39). Otherwise, whenever you try to do any operation with the `jsiRuntime` you might get the same thread error.

**Comment by jerson** [comment]
Hi @ospfranco thanks for report this issue, I didn't know about this possibility, I can take some time this weekend to apply this

**Comment by jerson** [comment]
@ospfranco thanks for the support, could you try using the new PR just created https://github.com/jerson/react-native-fast-openpgp/pull/101

**Comment by jerson** [comment]
new version released: https://www.npmjs.com/package/react-native-fast-openpgp/v/2.7.2 feel free to reopen the issue if needed
